version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      # - ./mongoData:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
  api:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_USER=api
      - MONGO_PASSWORD=apiPassword
      - DATABASE=gutendexer
      - GUTENDEX_URL=http://gutendex.com/books
    ports: 
      - 8000:8000
    restart: always
    
